name: Calculator

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter the first number'
        required: true
        type: number
      num2:
        description: 'Enter the second number'
        required: true
        type: number
      operator:
        description: 'Enter the operation '
        required: true
        default: ''
        type: choice
        options:
          - '+'
          - '-'
          - '*'
          - '/'
jobs:
  calculate_job:
    runs-on: windows-latest
    outputs:
      result: ${{ steps.result-output.outputs.result }}
    steps:
    - name: Run calculator
      id: result-output
      run: |
        $result = ${{ inputs.num1 }}${{ inputs.operator }}${{ inputs.num2 }}
        echo result=$result >> $env:GITHUB_OUTPUT
      
     
    
  
  display_result_job:
    needs: calculate_job
    runs-on: ubuntu-latest
    steps:

      - run: echo 'Result of calculation is ${{ needs.calculation.outputs.result }}'
